// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
)

type NpaPolicyResponse400 struct {
	Result *string `json:"result,omitempty"`
	Status *int64  `json:"status,omitempty"`
}

var _ error = &NpaPolicyResponse400{}

func (e *NpaPolicyResponse400) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
